packages:
  - apps/*
  - packages/*
  - ../../infra/kb-labs-devkit
  - ../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/packages/*
  - ../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-core/../kb-labs-devkit
  - ../kb-labs-core/apps/*
  - ../kb-labs-core/packages/*
  - ../kb-labs-studio/apps/*
  - ../kb-labs-studio/packages/*
